# Generated by Django 2.2 on 2019-04-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)])),
                ('count_point_ref', models.IntegerField()),
                ('estimation_method', models.IntegerField(choices=[(0, 'Counted'), (1, 'Estimated')])),
                ('estimation_method_detailed', models.IntegerField(choices=[(0, 'Manual count'), (1, 'Automatic counter'), (2, "Estimated using previous year's AADF on this link"), (3, 'Estimated from nearby links'), (4, 'Dependent on a neighbouring counted link')])),
                ('road', models.IntegerField(choices=[(0, 'A381'), (1, 'A386'), (2, 'A3125'), (3, 'A3052'), (4, 'A3123'), (5, 'A375'), (6, 'A39'), (7, 'A361'), (8, 'A382'), (9, 'M5'), (10, 'A3126'), (11, 'A384'), (12, 'A30'), (113, 'A380'), (14, 'A388'), (15, 'A383'), (16, 'A303'), (17, 'A3072'), (18, 'A3121'), (19, 'A35'), (20, 'A373'), (21, 'A3122'), (22, 'A38'), (23, 'A3079'), (24, 'A379'), (25, 'A376'), (26, 'A377'), (27, 'A390'), (28, 'A3124'), (29, 'A3015'), (30, 'A399'), (31, 'A396'), (32, 'A385'), (33, 'A358')])),
                ('road_category', models.IntegerField(choices=[(0, 'TA'), (1, 'PA'), (2, 'TM')])),
                ('easting', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('northing', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('junc_start', models.CharField(max_length=57)),
                ('junc_end', models.CharField(max_length=61)),
                ('len_net_km', models.FloatField()),
                ('len_net_mi', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.IntegerField(choices=[(0, 'AllHGVs'), (1, 'AllMotorVehicles'), (2, 'PedalCycles'), (3, 'Motorcycles'), (4, 'CarsTaxis'), (5, 'BusesCoaches'), (6, 'LightGoodsVehicles'), (7, 'V2AxleRigidHGV'), (8, 'V3AxleRigidHGV'), (9, 'V4or5AxleRigidHGV'), (10, 'V3or4AxleArticHGV'), (11, 'V5AxleArticHGV'), (12, 'V6orMoreAxleArticHGV')])),
                ('count', models.IntegerField()),
                ('record', models.ForeignKey(on_delete='CASCADE', to='traffic.Record')),
            ],
        ),
    ]
